spring:
  application:
    name: boxing-gym-api
  Kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
    consumer:
      group-id: boxing-gym-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.boxinggym.api.event"
        spring.json.value.default.type: "com.boxinggym.api.event.BookingEvent"
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/boxinggym}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update        # En producción usa 'validate' o Flyway
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: ${PORT:8080}          # Cloud Run inyecta PORT automáticamente

openai:
  api-key: ${OPENAI_API_KEY}
  model: gpt-4o-mini          # Económico y muy capaz
  url: https://api.openai.com/v1/chat/completions

management:
  endpoints:
    web:
      exposure:
        include: health       # Para health check de Cloud Run
